### ISSUE TITLE
backend 如何发送消息到设备时，是如何指定设备连接在哪个gateway上面的？

### ISSUE THREAD

**Issue by chowyu08** [hb-go/micro-mq#1]
主动下发消息的情况

**Comment by hb-chen** [comment]
现在没有指定设备发送，消息发送流程
- 先发送到broker
- Gateway上的设备订阅topic，Gateway再订阅broker
- 哪些Gateway订阅了，哪些就去消费broker的消息
- 再由Gateway将消息发送到订阅这个消息的设备

**Comment by chowyu08** [comment]
设备订阅的时候，gateway会订阅一个对应的topic到broker（kafka），这样topic会不会太多了

**Comment by hb-chen** [comment]
Gateway只订阅一级topic（比如a/b/c，Gateway订阅的是a），然后在消息里有完整topic

对，多个Gateway会消费相同的topic

**Comment by chowyu08** [comment]
这样的话，backend srv收到消息后，回复的响应没办法保证client能收到了

**Comment by hb-chen** [comment]
对，只代表broker将消息接收，而且只有实时在线的终端能够收到，适用场景比较有限
如果要保证订阅的client都能收到，需要做client订阅topic的持久化，client对消息的消费进度也要持久化，并且消息的消费变分散，这种是读放大；或者每个client都有一个消息待发送队列，也就是写放大。

大致这样的框架
![IoT](https://user-images.githubusercontent.com/730866/62514914-4a4f0600-b853-11e9-95ac-ac4119278a95.png)

**Comment by chowyu08** [comment]
好的，谢谢，非常棒的框架
